name: Release Obsidian plugin

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Read version from manifest.json
        id: manifest
        run: |
          VERSION=$(jq -r '.version' manifest.json)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build plugin
        run: |
          npm install
          npm run build

      - name: Create Git tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag -a "v${{ steps.manifest.outputs.version }}" -m "v${{ steps.manifest.outputs.version }}"
          git push origin "v${{ steps.manifest.outputs.version }}"

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="v${{ steps.manifest.outputs.version }}"

          gh release create "$tag" \
            --title="$tag" \
            --draft \
            main.js manifest.json styles.css